// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mainscreen.proto

package wormhole.lobby.network;

public final class MainScreenProto {
  private MainScreenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    JOIN_LOBBY(0, 0),
    CREATE_LOBBY(1, 1),
    LOBBY_LIST(2, 2),
    NEW_LOBBY(3, 3),
    REMOVED_LOBBY(4, 4),
    DISCONNECT(5, 6),
    ;
    
    public static final int JOIN_LOBBY_VALUE = 0;
    public static final int CREATE_LOBBY_VALUE = 1;
    public static final int LOBBY_LIST_VALUE = 2;
    public static final int NEW_LOBBY_VALUE = 3;
    public static final int REMOVED_LOBBY_VALUE = 4;
    public static final int DISCONNECT_VALUE = 6;
    
    
    public final int getNumber() { return value; }
    
    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return JOIN_LOBBY;
        case 1: return CREATE_LOBBY;
        case 2: return LOBBY_LIST;
        case 3: return NEW_LOBBY;
        case 4: return REMOVED_LOBBY;
        case 6: return DISCONNECT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return wormhole.lobby.network.MainScreenProto.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MessageType[] VALUES = {
      JOIN_LOBBY, CREATE_LOBBY, LOBBY_LIST, NEW_LOBBY, REMOVED_LOBBY, DISCONNECT, 
    };
    
    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:wormhole.MessageType)
  }
  
  public interface MainMessageTypeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .wormhole.MessageType type = 1;
    boolean hasType();
    wormhole.lobby.network.MainScreenProto.MessageType getType();
  }
  public static final class MainMessageType extends
      com.google.protobuf.GeneratedMessage
      implements MainMessageTypeOrBuilder {
    // Use MainMessageType.newBuilder() to construct.
    private MainMessageType(Builder builder) {
      super(builder);
    }
    private MainMessageType(boolean noInit) {}
    
    private static final MainMessageType defaultInstance;
    public static MainMessageType getDefaultInstance() {
      return defaultInstance;
    }
    
    public MainMessageType getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_MainMessageType_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_MainMessageType_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .wormhole.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private wormhole.lobby.network.MainScreenProto.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public wormhole.lobby.network.MainScreenProto.MessageType getType() {
      return type_;
    }
    
    private void initFields() {
      type_ = wormhole.lobby.network.MainScreenProto.MessageType.JOIN_LOBBY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.MainMessageType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wormhole.lobby.network.MainScreenProto.MainMessageType prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements wormhole.lobby.network.MainScreenProto.MainMessageTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_MainMessageType_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_MainMessageType_fieldAccessorTable;
      }
      
      // Construct using wormhole.lobby.network.MainScreenProto.MainMessageType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = wormhole.lobby.network.MainScreenProto.MessageType.JOIN_LOBBY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wormhole.lobby.network.MainScreenProto.MainMessageType.getDescriptor();
      }
      
      public wormhole.lobby.network.MainScreenProto.MainMessageType getDefaultInstanceForType() {
        return wormhole.lobby.network.MainScreenProto.MainMessageType.getDefaultInstance();
      }
      
      public wormhole.lobby.network.MainScreenProto.MainMessageType build() {
        wormhole.lobby.network.MainScreenProto.MainMessageType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private wormhole.lobby.network.MainScreenProto.MainMessageType buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        wormhole.lobby.network.MainScreenProto.MainMessageType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public wormhole.lobby.network.MainScreenProto.MainMessageType buildPartial() {
        wormhole.lobby.network.MainScreenProto.MainMessageType result = new wormhole.lobby.network.MainScreenProto.MainMessageType(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wormhole.lobby.network.MainScreenProto.MainMessageType) {
          return mergeFrom((wormhole.lobby.network.MainScreenProto.MainMessageType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(wormhole.lobby.network.MainScreenProto.MainMessageType other) {
        if (other == wormhole.lobby.network.MainScreenProto.MainMessageType.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              wormhole.lobby.network.MainScreenProto.MessageType value = wormhole.lobby.network.MainScreenProto.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .wormhole.MessageType type = 1;
      private wormhole.lobby.network.MainScreenProto.MessageType type_ = wormhole.lobby.network.MainScreenProto.MessageType.JOIN_LOBBY;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public wormhole.lobby.network.MainScreenProto.MessageType getType() {
        return type_;
      }
      public Builder setType(wormhole.lobby.network.MainScreenProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = wormhole.lobby.network.MainScreenProto.MessageType.JOIN_LOBBY;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:wormhole.MainMessageType)
    }
    
    static {
      defaultInstance = new MainMessageType(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wormhole.MainMessageType)
  }
  
  public interface LobbyIdMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 lobby_id = 1;
    boolean hasLobbyId();
    int getLobbyId();
  }
  public static final class LobbyIdMessage extends
      com.google.protobuf.GeneratedMessage
      implements LobbyIdMessageOrBuilder {
    // Use LobbyIdMessage.newBuilder() to construct.
    private LobbyIdMessage(Builder builder) {
      super(builder);
    }
    private LobbyIdMessage(boolean noInit) {}
    
    private static final LobbyIdMessage defaultInstance;
    public static LobbyIdMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public LobbyIdMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyIdMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyIdMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 lobby_id = 1;
    public static final int LOBBY_ID_FIELD_NUMBER = 1;
    private int lobbyId_;
    public boolean hasLobbyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getLobbyId() {
      return lobbyId_;
    }
    
    private void initFields() {
      lobbyId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLobbyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, lobbyId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, lobbyId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyIdMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wormhole.lobby.network.MainScreenProto.LobbyIdMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements wormhole.lobby.network.MainScreenProto.LobbyIdMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyIdMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyIdMessage_fieldAccessorTable;
      }
      
      // Construct using wormhole.lobby.network.MainScreenProto.LobbyIdMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lobbyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wormhole.lobby.network.MainScreenProto.LobbyIdMessage.getDescriptor();
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyIdMessage getDefaultInstanceForType() {
        return wormhole.lobby.network.MainScreenProto.LobbyIdMessage.getDefaultInstance();
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyIdMessage build() {
        wormhole.lobby.network.MainScreenProto.LobbyIdMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private wormhole.lobby.network.MainScreenProto.LobbyIdMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        wormhole.lobby.network.MainScreenProto.LobbyIdMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyIdMessage buildPartial() {
        wormhole.lobby.network.MainScreenProto.LobbyIdMessage result = new wormhole.lobby.network.MainScreenProto.LobbyIdMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.lobbyId_ = lobbyId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wormhole.lobby.network.MainScreenProto.LobbyIdMessage) {
          return mergeFrom((wormhole.lobby.network.MainScreenProto.LobbyIdMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(wormhole.lobby.network.MainScreenProto.LobbyIdMessage other) {
        if (other == wormhole.lobby.network.MainScreenProto.LobbyIdMessage.getDefaultInstance()) return this;
        if (other.hasLobbyId()) {
          setLobbyId(other.getLobbyId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLobbyId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              lobbyId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 lobby_id = 1;
      private int lobbyId_ ;
      public boolean hasLobbyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getLobbyId() {
        return lobbyId_;
      }
      public Builder setLobbyId(int value) {
        bitField0_ |= 0x00000001;
        lobbyId_ = value;
        onChanged();
        return this;
      }
      public Builder clearLobbyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        lobbyId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:wormhole.LobbyIdMessage)
    }
    
    static {
      defaultInstance = new LobbyIdMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wormhole.LobbyIdMessage)
  }
  
  public interface CreateLobbyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
  }
  public static final class CreateLobby extends
      com.google.protobuf.GeneratedMessage
      implements CreateLobbyOrBuilder {
    // Use CreateLobby.newBuilder() to construct.
    private CreateLobby(Builder builder) {
      super(builder);
    }
    private CreateLobby(boolean noInit) {}
    
    private static final CreateLobby defaultInstance;
    public static CreateLobby getDefaultInstance() {
      return defaultInstance;
    }
    
    public CreateLobby getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_CreateLobby_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_CreateLobby_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.CreateLobby parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wormhole.lobby.network.MainScreenProto.CreateLobby prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements wormhole.lobby.network.MainScreenProto.CreateLobbyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_CreateLobby_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_CreateLobby_fieldAccessorTable;
      }
      
      // Construct using wormhole.lobby.network.MainScreenProto.CreateLobby.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wormhole.lobby.network.MainScreenProto.CreateLobby.getDescriptor();
      }
      
      public wormhole.lobby.network.MainScreenProto.CreateLobby getDefaultInstanceForType() {
        return wormhole.lobby.network.MainScreenProto.CreateLobby.getDefaultInstance();
      }
      
      public wormhole.lobby.network.MainScreenProto.CreateLobby build() {
        wormhole.lobby.network.MainScreenProto.CreateLobby result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private wormhole.lobby.network.MainScreenProto.CreateLobby buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        wormhole.lobby.network.MainScreenProto.CreateLobby result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public wormhole.lobby.network.MainScreenProto.CreateLobby buildPartial() {
        wormhole.lobby.network.MainScreenProto.CreateLobby result = new wormhole.lobby.network.MainScreenProto.CreateLobby(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wormhole.lobby.network.MainScreenProto.CreateLobby) {
          return mergeFrom((wormhole.lobby.network.MainScreenProto.CreateLobby)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(wormhole.lobby.network.MainScreenProto.CreateLobby other) {
        if (other == wormhole.lobby.network.MainScreenProto.CreateLobby.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:wormhole.CreateLobby)
    }
    
    static {
      defaultInstance = new CreateLobby(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wormhole.CreateLobby)
  }
  
  public interface LobbyDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 id = 2;
    boolean hasId();
    int getId();
  }
  public static final class LobbyData extends
      com.google.protobuf.GeneratedMessage
      implements LobbyDataOrBuilder {
    // Use LobbyData.newBuilder() to construct.
    private LobbyData(Builder builder) {
      super(builder);
    }
    private LobbyData(boolean noInit) {}
    
    private static final LobbyData defaultInstance;
    public static LobbyData getDefaultInstance() {
      return defaultInstance;
    }
    
    public LobbyData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getId() {
      return id_;
    }
    
    private void initFields() {
      name_ = "";
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wormhole.lobby.network.MainScreenProto.LobbyData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyData_fieldAccessorTable;
      }
      
      // Construct using wormhole.lobby.network.MainScreenProto.LobbyData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wormhole.lobby.network.MainScreenProto.LobbyData.getDescriptor();
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyData getDefaultInstanceForType() {
        return wormhole.lobby.network.MainScreenProto.LobbyData.getDefaultInstance();
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyData build() {
        wormhole.lobby.network.MainScreenProto.LobbyData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private wormhole.lobby.network.MainScreenProto.LobbyData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        wormhole.lobby.network.MainScreenProto.LobbyData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyData buildPartial() {
        wormhole.lobby.network.MainScreenProto.LobbyData result = new wormhole.lobby.network.MainScreenProto.LobbyData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wormhole.lobby.network.MainScreenProto.LobbyData) {
          return mergeFrom((wormhole.lobby.network.MainScreenProto.LobbyData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(wormhole.lobby.network.MainScreenProto.LobbyData other) {
        if (other == wormhole.lobby.network.MainScreenProto.LobbyData.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 id = 2;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:wormhole.LobbyData)
    }
    
    static {
      defaultInstance = new LobbyData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wormhole.LobbyData)
  }
  
  public interface LobbyDataListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .wormhole.LobbyData lobby = 1;
    java.util.List<wormhole.lobby.network.MainScreenProto.LobbyData> 
        getLobbyList();
    wormhole.lobby.network.MainScreenProto.LobbyData getLobby(int index);
    int getLobbyCount();
    java.util.List<? extends wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder> 
        getLobbyOrBuilderList();
    wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder getLobbyOrBuilder(
        int index);
  }
  public static final class LobbyDataList extends
      com.google.protobuf.GeneratedMessage
      implements LobbyDataListOrBuilder {
    // Use LobbyDataList.newBuilder() to construct.
    private LobbyDataList(Builder builder) {
      super(builder);
    }
    private LobbyDataList(boolean noInit) {}
    
    private static final LobbyDataList defaultInstance;
    public static LobbyDataList getDefaultInstance() {
      return defaultInstance;
    }
    
    public LobbyDataList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyDataList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyDataList_fieldAccessorTable;
    }
    
    // repeated .wormhole.LobbyData lobby = 1;
    public static final int LOBBY_FIELD_NUMBER = 1;
    private java.util.List<wormhole.lobby.network.MainScreenProto.LobbyData> lobby_;
    public java.util.List<wormhole.lobby.network.MainScreenProto.LobbyData> getLobbyList() {
      return lobby_;
    }
    public java.util.List<? extends wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder> 
        getLobbyOrBuilderList() {
      return lobby_;
    }
    public int getLobbyCount() {
      return lobby_.size();
    }
    public wormhole.lobby.network.MainScreenProto.LobbyData getLobby(int index) {
      return lobby_.get(index);
    }
    public wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder getLobbyOrBuilder(
        int index) {
      return lobby_.get(index);
    }
    
    private void initFields() {
      lobby_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getLobbyCount(); i++) {
        if (!getLobby(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < lobby_.size(); i++) {
        output.writeMessage(1, lobby_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < lobby_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, lobby_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static wormhole.lobby.network.MainScreenProto.LobbyDataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(wormhole.lobby.network.MainScreenProto.LobbyDataList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements wormhole.lobby.network.MainScreenProto.LobbyDataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyDataList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return wormhole.lobby.network.MainScreenProto.internal_static_wormhole_LobbyDataList_fieldAccessorTable;
      }
      
      // Construct using wormhole.lobby.network.MainScreenProto.LobbyDataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLobbyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (lobbyBuilder_ == null) {
          lobby_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          lobbyBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return wormhole.lobby.network.MainScreenProto.LobbyDataList.getDescriptor();
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyDataList getDefaultInstanceForType() {
        return wormhole.lobby.network.MainScreenProto.LobbyDataList.getDefaultInstance();
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyDataList build() {
        wormhole.lobby.network.MainScreenProto.LobbyDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private wormhole.lobby.network.MainScreenProto.LobbyDataList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        wormhole.lobby.network.MainScreenProto.LobbyDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public wormhole.lobby.network.MainScreenProto.LobbyDataList buildPartial() {
        wormhole.lobby.network.MainScreenProto.LobbyDataList result = new wormhole.lobby.network.MainScreenProto.LobbyDataList(this);
        int from_bitField0_ = bitField0_;
        if (lobbyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            lobby_ = java.util.Collections.unmodifiableList(lobby_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.lobby_ = lobby_;
        } else {
          result.lobby_ = lobbyBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof wormhole.lobby.network.MainScreenProto.LobbyDataList) {
          return mergeFrom((wormhole.lobby.network.MainScreenProto.LobbyDataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(wormhole.lobby.network.MainScreenProto.LobbyDataList other) {
        if (other == wormhole.lobby.network.MainScreenProto.LobbyDataList.getDefaultInstance()) return this;
        if (lobbyBuilder_ == null) {
          if (!other.lobby_.isEmpty()) {
            if (lobby_.isEmpty()) {
              lobby_ = other.lobby_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLobbyIsMutable();
              lobby_.addAll(other.lobby_);
            }
            onChanged();
          }
        } else {
          if (!other.lobby_.isEmpty()) {
            if (lobbyBuilder_.isEmpty()) {
              lobbyBuilder_.dispose();
              lobbyBuilder_ = null;
              lobby_ = other.lobby_;
              bitField0_ = (bitField0_ & ~0x00000001);
              lobbyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLobbyFieldBuilder() : null;
            } else {
              lobbyBuilder_.addAllMessages(other.lobby_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getLobbyCount(); i++) {
          if (!getLobby(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              wormhole.lobby.network.MainScreenProto.LobbyData.Builder subBuilder = wormhole.lobby.network.MainScreenProto.LobbyData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLobby(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .wormhole.LobbyData lobby = 1;
      private java.util.List<wormhole.lobby.network.MainScreenProto.LobbyData> lobby_ =
        java.util.Collections.emptyList();
      private void ensureLobbyIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          lobby_ = new java.util.ArrayList<wormhole.lobby.network.MainScreenProto.LobbyData>(lobby_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          wormhole.lobby.network.MainScreenProto.LobbyData, wormhole.lobby.network.MainScreenProto.LobbyData.Builder, wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder> lobbyBuilder_;
      
      public java.util.List<wormhole.lobby.network.MainScreenProto.LobbyData> getLobbyList() {
        if (lobbyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(lobby_);
        } else {
          return lobbyBuilder_.getMessageList();
        }
      }
      public int getLobbyCount() {
        if (lobbyBuilder_ == null) {
          return lobby_.size();
        } else {
          return lobbyBuilder_.getCount();
        }
      }
      public wormhole.lobby.network.MainScreenProto.LobbyData getLobby(int index) {
        if (lobbyBuilder_ == null) {
          return lobby_.get(index);
        } else {
          return lobbyBuilder_.getMessage(index);
        }
      }
      public Builder setLobby(
          int index, wormhole.lobby.network.MainScreenProto.LobbyData value) {
        if (lobbyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLobbyIsMutable();
          lobby_.set(index, value);
          onChanged();
        } else {
          lobbyBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLobby(
          int index, wormhole.lobby.network.MainScreenProto.LobbyData.Builder builderForValue) {
        if (lobbyBuilder_ == null) {
          ensureLobbyIsMutable();
          lobby_.set(index, builderForValue.build());
          onChanged();
        } else {
          lobbyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLobby(wormhole.lobby.network.MainScreenProto.LobbyData value) {
        if (lobbyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLobbyIsMutable();
          lobby_.add(value);
          onChanged();
        } else {
          lobbyBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLobby(
          int index, wormhole.lobby.network.MainScreenProto.LobbyData value) {
        if (lobbyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLobbyIsMutable();
          lobby_.add(index, value);
          onChanged();
        } else {
          lobbyBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLobby(
          wormhole.lobby.network.MainScreenProto.LobbyData.Builder builderForValue) {
        if (lobbyBuilder_ == null) {
          ensureLobbyIsMutable();
          lobby_.add(builderForValue.build());
          onChanged();
        } else {
          lobbyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLobby(
          int index, wormhole.lobby.network.MainScreenProto.LobbyData.Builder builderForValue) {
        if (lobbyBuilder_ == null) {
          ensureLobbyIsMutable();
          lobby_.add(index, builderForValue.build());
          onChanged();
        } else {
          lobbyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLobby(
          java.lang.Iterable<? extends wormhole.lobby.network.MainScreenProto.LobbyData> values) {
        if (lobbyBuilder_ == null) {
          ensureLobbyIsMutable();
          super.addAll(values, lobby_);
          onChanged();
        } else {
          lobbyBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLobby() {
        if (lobbyBuilder_ == null) {
          lobby_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          lobbyBuilder_.clear();
        }
        return this;
      }
      public Builder removeLobby(int index) {
        if (lobbyBuilder_ == null) {
          ensureLobbyIsMutable();
          lobby_.remove(index);
          onChanged();
        } else {
          lobbyBuilder_.remove(index);
        }
        return this;
      }
      public wormhole.lobby.network.MainScreenProto.LobbyData.Builder getLobbyBuilder(
          int index) {
        return getLobbyFieldBuilder().getBuilder(index);
      }
      public wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder getLobbyOrBuilder(
          int index) {
        if (lobbyBuilder_ == null) {
          return lobby_.get(index);  } else {
          return lobbyBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder> 
           getLobbyOrBuilderList() {
        if (lobbyBuilder_ != null) {
          return lobbyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(lobby_);
        }
      }
      public wormhole.lobby.network.MainScreenProto.LobbyData.Builder addLobbyBuilder() {
        return getLobbyFieldBuilder().addBuilder(
            wormhole.lobby.network.MainScreenProto.LobbyData.getDefaultInstance());
      }
      public wormhole.lobby.network.MainScreenProto.LobbyData.Builder addLobbyBuilder(
          int index) {
        return getLobbyFieldBuilder().addBuilder(
            index, wormhole.lobby.network.MainScreenProto.LobbyData.getDefaultInstance());
      }
      public java.util.List<wormhole.lobby.network.MainScreenProto.LobbyData.Builder> 
           getLobbyBuilderList() {
        return getLobbyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          wormhole.lobby.network.MainScreenProto.LobbyData, wormhole.lobby.network.MainScreenProto.LobbyData.Builder, wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder> 
          getLobbyFieldBuilder() {
        if (lobbyBuilder_ == null) {
          lobbyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              wormhole.lobby.network.MainScreenProto.LobbyData, wormhole.lobby.network.MainScreenProto.LobbyData.Builder, wormhole.lobby.network.MainScreenProto.LobbyDataOrBuilder>(
                  lobby_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          lobby_ = null;
        }
        return lobbyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:wormhole.LobbyDataList)
    }
    
    static {
      defaultInstance = new LobbyDataList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:wormhole.LobbyDataList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wormhole_MainMessageType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wormhole_MainMessageType_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wormhole_LobbyIdMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wormhole_LobbyIdMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wormhole_CreateLobby_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wormhole_CreateLobby_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wormhole_LobbyData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wormhole_LobbyData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_wormhole_LobbyDataList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_wormhole_LobbyDataList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020mainscreen.proto\022\010wormhole\"6\n\017MainMess" +
      "ageType\022#\n\004type\030\001 \002(\0162\025.wormhole.Message" +
      "Type\"\"\n\016LobbyIdMessage\022\020\n\010lobby_id\030\001 \002(\005" +
      "\"\033\n\013CreateLobby\022\014\n\004name\030\001 \002(\t\"%\n\tLobbyDa" +
      "ta\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\"3\n\rLobbyDat" +
      "aList\022\"\n\005lobby\030\001 \003(\0132\023.wormhole.LobbyDat" +
      "a*q\n\013MessageType\022\016\n\nJOIN_LOBBY\020\000\022\020\n\014CREA" +
      "TE_LOBBY\020\001\022\016\n\nLOBBY_LIST\020\002\022\r\n\tNEW_LOBBY\020" +
      "\003\022\021\n\rREMOVED_LOBBY\020\004\022\016\n\nDISCONNECT\020\006B)\n\026" +
      "wormhole.lobby.networkB\017MainScreenProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_wormhole_MainMessageType_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_wormhole_MainMessageType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wormhole_MainMessageType_descriptor,
              new java.lang.String[] { "Type", },
              wormhole.lobby.network.MainScreenProto.MainMessageType.class,
              wormhole.lobby.network.MainScreenProto.MainMessageType.Builder.class);
          internal_static_wormhole_LobbyIdMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_wormhole_LobbyIdMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wormhole_LobbyIdMessage_descriptor,
              new java.lang.String[] { "LobbyId", },
              wormhole.lobby.network.MainScreenProto.LobbyIdMessage.class,
              wormhole.lobby.network.MainScreenProto.LobbyIdMessage.Builder.class);
          internal_static_wormhole_CreateLobby_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_wormhole_CreateLobby_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wormhole_CreateLobby_descriptor,
              new java.lang.String[] { "Name", },
              wormhole.lobby.network.MainScreenProto.CreateLobby.class,
              wormhole.lobby.network.MainScreenProto.CreateLobby.Builder.class);
          internal_static_wormhole_LobbyData_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_wormhole_LobbyData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wormhole_LobbyData_descriptor,
              new java.lang.String[] { "Name", "Id", },
              wormhole.lobby.network.MainScreenProto.LobbyData.class,
              wormhole.lobby.network.MainScreenProto.LobbyData.Builder.class);
          internal_static_wormhole_LobbyDataList_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_wormhole_LobbyDataList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_wormhole_LobbyDataList_descriptor,
              new java.lang.String[] { "Lobby", },
              wormhole.lobby.network.MainScreenProto.LobbyDataList.class,
              wormhole.lobby.network.MainScreenProto.LobbyDataList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
